### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by matyklugDebbuged** [matyklugDebbuged/Aqarium#1]
- [ ] create functional coal generator using FE
- [ ] create functional magma generator
- [ ] create energy cable
- [ ] create some sort of energy cube
- [ ] create energy smelter
- [ ] make everything configurable
- [ ] add chest
- [ ]
- [ ]
- [ ]
- [ ]
- [ ]
